const movies = [
  {
    id: 1,
    title: "ساختمان پزشکان",
    dateCreated: "2020-05-12T15:17:43.957Z",
    genre: ["کمدی", "اجتماعی"],
    episode: 18,
    category: "serial",
    actors: ["بهنام تشکر", "بیژن بنفشه‌خواه", "شقایق دهقان", "هومن برق‌نورد"],
    image: "../assets/images/film/Sakhteman-Pezeshkan.jpg",
  },
  {
    id: 2,
    title: "خانه به دوش",
    dateCreated: "2018-05-12T15:17:43.957Z",
    genre: ["کمدی"],
    episode: 10,
    category: "serial",
    actors: ["حمید لولایی", "مریم امیرجلالی"],
    image: "../assets/images/film/khane-be-dush.jfif",
  },
  {
    id: 3,
    title: "نهنگ عنبر",
    dateCreated: "2015-05-12T15:17:43.957Z",
    genre: ["کمدی", "خانوادگی"],
    episode: 1,
    category: "movie",
    actors: ["رضا عطاران", "مهناز افشار"],
    image: "../assets/images/film/nahang.jfif",
  },
  {
    id: 4,
    title: "مست عشق",
    dateCreated: "2021-05-12T15:17:43.957Z",
    genre: ["تاریخی", "حماسی"],
    episode: 1,
    category: "movie",
    actors: ["پارسا پیروزفر", "شهاب حسینی", ""],
    image: "../assets/images/film/mast-eshgh.jpg",
  },
  {
    id: 5,
    title: "Road House",
    dateCreated: "2021-05-12T15:17:43.957Z",
    genre: ["اکشن", "ماجراجویی"],
    episode: 1,
    category: "movie",
    actors: ["Jake Gyllenhaal", "Daniela Melchior"],
    image: "../assets/images/film/road.jfif",
  },
  {
    id: 6,
    title: "war",
    dateCreated: "2021-05-12T15:17:43.957Z",
    genre: ["جنگی"],
    episode: 1,
    category: "movie",
    actors: ["Liam Hemsworth", "Russell Crowe"],
    image: "../assets/images/film/war.jfif",
  },
  {
    id: 7,
    title: "Godzilla",
    dateCreated: "2021-05-12T15:17:43.957Z",
    genre: ["علمی تخیلی", "اکشن"],
    episode: 1,
    category: "movie",
    actors: ["Liam Hemsworth", "Russell Crowe"],
    image: "../assets/images/film/godzilla.jfif",
  },
];
export default movies;
